

stages:
  - build
  - publish


build:
  stage: build
  image: pytorch/conda-cuda
  script:
    - conda install -y -c pytorch pytorch=1.1 python=3.7
    - conda install -y conda-build conda-verify
    - conda build conda/ -c defaults -c pytorch -c conda-forge -c aahendriksen
    - mkdir -p artifacts
    - mv /root/miniconda3/conda-bld/linux-64/msd_pytorch*.bz2 artifacts/
  artifacts:
    paths:
    - artifacts/
    expire_in: 7 days

publish:
  stage: publish
  only:
  - tags
  variables:
    ANACONDA_USERNAME: $ANACONDA_USERNAME
    ANACONDA_PASSWORD: $ANACONDA_PASSWORD
  script:
    - conda install -yq anaconda-client
    - set +x
    - anaconda login --username "$ANACONDA_USERNAME" --password "$ANACONDA_PASSWORD"
    - set -x
    - anaconda upload artifacts/*.bz2
