c_compiler_version:    # [linux]
  - 7.3                # [linux]
cxx_compiler_version:  # [linux]
  - 7.3                # [linux]
python:
  - 3.6
  - 3.7
cudatoolkit:
  - 10.0    # 10.1 is not supported by pytorch 1.1
  - 9.2
